import 'lang_keys.dart';

const Map<String, String> ar = {
  ar_Login: 'تسجيل الدخول',
  ar_Signup: 'انشاء حساب',
  kWatch: 'انتبه!',
  kLogout: 'تسجيل خروج',
  kMail: 'البريد الالكتروني',
  kPass: 'كلمة المرور',
  kPassWar: ' كلمة المرور فارغة',
  kMailWar: ' البريد الالكتروني فارغ',
  kFields_war: 'ادخل المعلوكات المطلوبة',
  ar_instructions: 'التعليمات والمعادلات',
  ar_app_name: 'حاسبة الجرعات',
  ar_home: 'الرئيسية',
  ar_contact_us: 'تواصل معنا',
  ar_equations: 'المعادلات والتعليمات',
  ar_dark_mode: 'الوضع الليلي',
  ar_support_us: 'ادعمنا',
  ar_our_apps: 'تطبيقات اخرى',
  ar_language: 'اللفة',
  ar_antibiotics: 'المضاد الحيوي',
  ar_antibyretics: 'خافض الحرارة',
  ar_injections: 'الحقن',
  ar_weight: 'الوزن',
  ar_weight_is: 'الوزن',
  ar_kg: 'كجم',
  ar_ml: ' مل ',
  ar_recent: 'recent',
  ar_every: 'كل',
  ar_months: 'شهور',
  ar_years: 'سنوات',
  ar_change: 'غير',
  ar_calculate: 'احسب',
  ar_result: 'النتيجه',
  ar_mg: 'مجم',
  ar_hr: 'ساعه',
  ar_copied: 'تم النسخ الى الحافظة',
  ar_but: 'لكن',
  ar_rate_us: 'قيمنا',
  ar_the_dose_is: 'الجرعة هي',
  ar_the_suitable_vial: 'الجرعة المناسبه هي ١٠٠٠',
  ar_valid_months: 'ادخل الشهور بين ١ - ١٢',
  ar_valid_years: 'ادخل السنوات بين ١ - ٣',
  ar_buy_pro: 'شراء النسخه المحسنه',
  ar_choose_medicine: 'اختر الدواء',
  ar_search_medicine: 'ابحث عن الدواء',
  ar_choose_medicine_first: 'اختر دواء أولا',
  ar_choose_weight_first: 'ادخل الوزن أولا',
  ar_antobiotic_name: 'اسم المضاد الحيوي',
  ar_amoxicilin_war: 'امكسوسيلين كلافيلونك غير مسموح به تحت سن ٩ اشهر (او وزن ٨.٥ كجم)',
  ar_declophanic_war: 'الديكلوفنات غير مسموح بها تحت سن سنة ( ١٠ كجم)',
  ar_ibuprofen_war: 'ايبوبروفين غير مسموح به تحت  ٦ اشهر (٧ كجم)',
  ar_refrence:
      'المصدر: كتاب تسهيل طب الاطفال للدكتور سامح الشرنوبي, معادلة المضاد الحيوي و خافض الحرارة: (لو تعرف الوزن) الناتج = (الوزن * الجرعة/كجم * 5) /(التركيز * عدد الجرعات)',
  ar_eq2:
      '( لو لا تعرف الوزن لكن تعرف العمر بالشهور ):  الوزن = (العمر بالشهور + 9 ) / 2 - 1/2 هذه المعادلة صالحة من شهر حنى 12 شهر',
  ar_eq3:
      '( لو لا تعرف الوزن لكن تعرف العمر بالسنوات):  الوزن = (العمر بالسنوات * 2 ) + 8  هذه المعادلة صالحة من سنة حنى 3 سنوات',
  ar_dose_weight_eq: 'الناتج = (الوزن * الجرعة/كجم * 5) /(التركيز * عدد الجرعات)',
  ar_warn2: 'لاحظ ان معادلات الوزن هي تقريبية والافضل معرفة الوزن عبر الميزان ',
  ar_warn3: 'امكسوسيلين كلافيولونك غير مسموح بها تحت سن  9اشهر  ( 8.5 كجم)  ',
  ar_warn4: 'الديكلوفنات غير مسموح بها تحت سن سنة ( 10 كجم)  و ايبوبروفين غير مسموح به تحت  6 اشهر (7 كجم) ',

  // antibiotic
  ar_amoxicillin228: 'حمض اموكسيسيلين كلافيلونك ٢٢٨.٥ مجم / ٥ مل',
  ar_amoxicillin312: 'حمض اموكسيسيلين كلافيلونك ٣١٢ مجم / ٥ مل',
  ar_amoxicillin457: 'حمض اموكسيسيلين كلافيلونك ٤٥٧ مجم / ٥ مل',
  ar_amoxicillin600: 'حمض اموكسيسيلين كلافيلونك ٦٠٠ مجم / ٥ مل',

  ar_azithromycin100: 'ازيثروميسين ١٠٠ مجم / ٥ مل',
  ar_azithromycin200: 'ازيثروميسين ٢٠٠ مجم / ٥ مل',

  ar_cafaclor125: 'سيفاكلور ١٢٥ مجم / ٥ مل',
  ar_cafaclor250: 'سيفاكلور ٢٥٠ مجم / ٥ مل',

  ar_Cafprozil125: 'سيفبروزيل ١٢٥ مجم / ٥ مل',
  ar_Cafprozil250: 'سيفبروزيل ٥٠٠ مجم / ٥ مل',

  ar_Cefalexin125: 'سيفالكسين(كيفلكس) ١٢٥ مجم / ٥ مل',
  ar_Cefalexin250: 'سيفالكسين(كيفلكس) ٢٥٠ مجم / ٥ مل',

  ar_Cefadroxill125: 'سيفادروكسيل (ديورسبف)  ١٢٥ مجم / ٥ مل',
  ar_Cefadroxill250: 'سيفادروكسيل (ديورسبف) ٢٥٠ مجم / ٥ مل',
  ar_Cefadroxill500: 'سيفادروكسيل (ديورسبف) ٥٠٠ مجم / ٥ مل',

  ar_Cefiximel100: 'سيفيكسيم ١٠٠ مجم / ٥ مل',
  ar_Cefdinir125: 'سيفدينير ١٢٥ مجم / ٥ مل',
  ar_Cefdinir250: 'سيفدينير ٢٥٠ مجم / ٥ مل',
  // antipyretic
  ar_Ibuprofen100: 'ايبوبروفين ١٠٠ مجم / ٥ مل',
  ar_Paracetamol250: 'بارسيتامول (سيتال) ٢٥٠ مجم / ٥ مل',
  ar_Declophenac2: 'ديكلوفانك ٢ مجم / ١ مل',
  // injection
  ar_Ampicillin: 'امبسيلين سلباكتم ١٥٠ مجم / كجم',
  ar_Ceftriaxone: 'سيفترياكسون ٥٠ مجم / كجم',
  ar_Cefotaxime: 'سيفوتكسيم ١٠٠ مجم / كجم',
  ar_Cefoperazone: 'سيفوبيرازون ١٠٠ مجم / كجم',

  // contact us
  ar_dr_sherief_name : 'دكتور شريف خالد',
  ar_dr_sherief_email : 'sherifkhaled469@gmail.com',
  ar_dr_sherief_phone : '01065060882',
  ar_eng_abdo_name : 'مهندس عبد الرحمن طارق',
  ar_eng_abdo_email : 'abdotarekfathy@gmail.com',
  ar_eng_abdo_phone : '01061420874',
};
